# Generated by Django 5.0.1 on 2024-02-02 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('type_doc', models.CharField(choices=[('TI', 'TI'), ('CC', 'CC'), ('CE', 'CE')], max_length=50, unique=True)),
                ('doc_number', models.CharField(max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=50, unique=True)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('privacity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
