# Generated by Django 5.0.1 on 2024-02-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_form_gender_alter_form_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='select_plan',
            field=models.CharField(default='Clase gratis', max_length=100),
        ),
    ]
