# Generated by Django 5.0.1 on 2024-02-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_form_select_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='select_plan',
            field=models.CharField(max_length=100),
        ),
    ]
