# Generated by Django 5.0.1 on 2024-02-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_form_select_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='select_plan',
        ),
    ]
