from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.utils.html import format_html

def send_confirmation_email(full_name, email, phone, type_doc, doc_number, occupation, gender, select_plan):
    subject = '¡Bienvenido(a) al Curso de Diseño de Cejas!'
    message_text = f'Hola {full_name}, Tu viaje en el Curso de Diseño de Cejas ha comenzado. ¡Prepárate para descubrir el arte del diseño de cejas y mejorar tus habilidades! 🌟'

    message_html = format_html('''
        <html><head><style>.container{{font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;background-color:#8f8f8f46;max-width:600px;margin:0 auto;padding:20px;background-size:cover;background-position:center;backdrop-filter:blur(20px)}}h1{{font-size:32px;font-weight:700;color:#000;margin-bottom:30px;text-align:center;backdrop-filter:blur(2px);text-shadow:1px 1px #535353}}p{{font-size:18px;color:#4b4b4b;line-height:1.5;margin-bottom:20px}}.highlight{{background:linear-gradient(to right,#2fa3c0,#1559d6);color:#fff;padding:10px 20px;border-radius:6px}}.logo{{display:block;margin:0 auto;max-width:100px;border:none;box-shadow:0 0 20px rgba(0,0,0,.2)}}.footer{{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen,Ubuntu,Cantarell,"Open Sans","Helvetica Neue",sans-serif;font-size:15px;padding-left:5px}}</style></head><body><div class="container"><table style="width:100%"><tr><td style="text-align:center"><img src="https://www.hygmicropigmentacion.com/wp-content/uploads/2022/08/Trasparente-Oscuro.png" alt="Logo" class="logo"></td></tr></table><h1>Confirmación de Curso diseño de cejas</h1><p>Hola {full_name},</p><p>Es un placer darle la bienvenida a nuestro Curso de Diseño de Cejas. En<a href="https://www.hygmicropigmentacion.com/">H&G Micropigmentación</a>, estamos emocionados de tenerlo(a) como parte de nuestra comunidad de aprendizaje🤓📓. Este curso está diseñado para proporcionarle las habilidades y conocimientos necesarios para convertirse en un experto en el diseño de cejas✅.</p><p class="highlight">⚠️!Si ha elegido la inscripción de pago, a continuacion se muestra el detalle de los medios de pago disponibles!👀</p><p>Estamos comprometidos a brindarle una experiencia educativa excepcional y estamos emocionados de acompañarlo(a) en su viaje de aprendizaje.</p><p>¡Esperamos que disfrute del curso y que obtenga habilidades valiosas en el diseño de cejas!</p><p class="footer">Saludos cordiales,<br>Giovanni<br>[Posición en la Empresa]<br>H&G Micropigmentación<br>Contacto: +57 3165407711</p></div></body></html>
    ''', full_name=full_name)

    email = EmailMultiAlternatives(subject, message_text, 'contacto@hygmicropigmentacion.com', [email])
    email.attach_alternative(message_html, "text/html")
    email.send()

    # Send email to manager
    manager_email = '13mediafirecuenta@gmail.com'
    submanager_email = 'iproofpython@gmail.com'
    manager_subject = 'Nuevo usuario registrado'

    manager_message_html = format_html('''
        <html><div style="margin:auto;max-width:600px;padding-top:50px" class="m_-6687661799313084825email-container"><table role="presentation" id="m_-6687661799313084825logoContainer" style="background:#252f3d;border-radius:3px 3px 0 0;max-width:600px" width="100%" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td style="background:#c5c5c5;border-radius:3px 3px 0 0;padding:20px 0 10px 0;text-align:center"><img src="https://www.hygmicropigmentacion.com/wp-content/uploads/2022/08/Trasparente-Oscuro.png" alt="AWS logo" style="font-family:sans-serif;font-size:15px;line-height:140%;color:#555" data-bit="iit" width="65" height="65" border="0"></td></tr></tbody></table><table style="border:0;border-bottom:1px solid #d6d6d6;max-width:600px" width="100%" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td style="background-color:#fff;color:#444;font-family:'Amazon Ember','Helvetica Neue',Roboto,Arial,sans-serif;font-size:14px;line-height:140%;padding:25px 35px"><h1 style="font-size:20px;font-weight:700;line-height:1.3;margin:0 0 15px 0">Nuevo usuario registrado</h1><p style="margin:0;padding:0">Nombre : {full_name}<br>Correo electrónico : {email}<br>Número de WhatsApp : {phone}<br>Tipo de documento : {type_doc}<br>Número de documento : {doc_number}<br>Profesión / Estudio realizado : {occupation}<br>Genero : {gender}<br>Plan Seleccionado : {select_plan}</p><p style="margin:0;padding:0"></p></td></tr></tbody></table><table style="max-width:600px" width="100%" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td style="color:#777;font-family:'Amazon Ember','Helvetica Neue',Roboto,Arial,sans-serif;font-size:12px;line-height:16px;padding:20px 30px;text-align:center">Este mensaje fue producido y creado por H&G Micropigmentación. © 2024, Todos los derechos reservados. Si deseas ver más detalles de la reserva creada, ingresa<a href="https://www.hygmicropigmentacion.com/" target="_blank">aquí</a>.</td></tr></tbody></table></div></html>
    ''', full_name=full_name, email=email, type_doc=type_doc, phone=phone, doc_number=doc_number, occupation=occupation, gender=gender, select_plan=select_plan)

    manager_email = EmailMultiAlternatives(manager_subject, '', 'contacto@hygmicropigmentacion.com', [manager_email, submanager_email])
    manager_email.attach_alternative(manager_message_html, "text/html")
    manager_email.send()